// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mondis.proto

package mondis;

public final class Mondis {
  private Mondis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *命令执行结果
   * </pre>
   *
   * Protobuf enum {@code mondis.ExecResType}
   */
  public enum ExecResType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>SYNTAX_ERROR = 1;</code>
     */
    SYNTAX_ERROR(1),
    /**
     * <code>INTERNAL_ERROR = 2;</code>
     */
    INTERNAL_ERROR(2),
    /**
     * <code>LOGIC_ERROR = 3;</code>
     */
    LOGIC_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>SYNTAX_ERROR = 1;</code>
     */
    public static final int SYNTAX_ERROR_VALUE = 1;
    /**
     * <code>INTERNAL_ERROR = 2;</code>
     */
    public static final int INTERNAL_ERROR_VALUE = 2;
    /**
     * <code>LOGIC_ERROR = 3;</code>
     */
    public static final int LOGIC_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExecResType valueOf(int value) {
      return forNumber(value);
    }

    public static ExecResType forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return SYNTAX_ERROR;
        case 2: return INTERNAL_ERROR;
        case 3: return LOGIC_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecResType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExecResType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecResType>() {
            public ExecResType findValueByNumber(int number) {
              return ExecResType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mondis.Mondis.getDescriptor().getEnumTypes().get(0);
    }

    private static final ExecResType[] VALUES = values();

    public static ExecResType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExecResType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mondis.ExecResType)
  }

  /**
   * <pre>
   *通信消息类型
   * </pre>
   *
   * Protobuf enum {@code mondis.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA = 0;</code>
     */
    DATA(0),
    /**
     * <code>COMMAND = 1;</code>
     */
    COMMAND(1),
    /**
     * <code>EXEC_RES = 2;</code>
     */
    EXEC_RES(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DATA = 0;</code>
     */
    public static final int DATA_VALUE = 0;
    /**
     * <code>COMMAND = 1;</code>
     */
    public static final int COMMAND_VALUE = 1;
    /**
     * <code>EXEC_RES = 2;</code>
     */
    public static final int EXEC_RES_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return DATA;
        case 1: return COMMAND;
        case 2: return EXEC_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mondis.Mondis.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mondis.MsgType)
  }

  /**
   * <pre>
   *数据类型
   * </pre>
   *
   * Protobuf enum {@code mondis.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYNC_DATA = 0;</code>
     */
    SYNC_DATA(0),
    /**
     * <code>CONTROL_MSG = 1;</code>
     */
    CONTROL_MSG(1),
    /**
     * <code>HEART_BEAT = 2;</code>
     */
    HEART_BEAT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SYNC_DATA = 0;</code>
     */
    public static final int SYNC_DATA_VALUE = 0;
    /**
     * <code>CONTROL_MSG = 1;</code>
     */
    public static final int CONTROL_MSG_VALUE = 1;
    /**
     * <code>HEART_BEAT = 2;</code>
     */
    public static final int HEART_BEAT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return SYNC_DATA;
        case 1: return CONTROL_MSG;
        case 2: return HEART_BEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mondis.Mondis.getDescriptor().getEnumTypes().get(2);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mondis.DataType)
  }

  /**
   * <pre>
   *命令类型
   * </pre>
   *
   * Protobuf enum {@code mondis.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLIENT_COMMAND = 0;</code>
     */
    CLIENT_COMMAND(0),
    /**
     * <code>MASTER_COMMAND = 1;</code>
     */
    MASTER_COMMAND(1),
    /**
     * <code>PEER_COMMAND = 2;</code>
     */
    PEER_COMMAND(2),
    /**
     * <code>SLAVE_FORWARD = 3;</code>
     */
    SLAVE_FORWARD(3),
    /**
     * <code>TIMER_COMMAND = 4;</code>
     */
    TIMER_COMMAND(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLIENT_COMMAND = 0;</code>
     */
    public static final int CLIENT_COMMAND_VALUE = 0;
    /**
     * <code>MASTER_COMMAND = 1;</code>
     */
    public static final int MASTER_COMMAND_VALUE = 1;
    /**
     * <code>PEER_COMMAND = 2;</code>
     */
    public static final int PEER_COMMAND_VALUE = 2;
    /**
     * <code>SLAVE_FORWARD = 3;</code>
     */
    public static final int SLAVE_FORWARD_VALUE = 3;
    /**
     * <code>TIMER_COMMAND = 4;</code>
     */
    public static final int TIMER_COMMAND_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return CLIENT_COMMAND;
        case 1: return MASTER_COMMAND;
        case 2: return PEER_COMMAND;
        case 3: return SLAVE_FORWARD;
        case 4: return TIMER_COMMAND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mondis.Mondis.getDescriptor().getEnumTypes().get(3);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mondis.CommandType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mondis.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.mondis.MsgType msg_type = 1;</code>
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.mondis.MsgType msg_type = 1;</code>
     */
    mondis.Mondis.MsgType getMsgType();

    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *执行结果类型
     * </pre>
     *
     * <code>.mondis.ExecResType res_type = 3;</code>
     */
    int getResTypeValue();
    /**
     * <pre>
     *执行结果类型
     * </pre>
     *
     * <code>.mondis.ExecResType res_type = 3;</code>
     */
    mondis.Mondis.ExecResType getResType();

    /**
     * <pre>
     *数据类型
     * </pre>
     *
     * <code>.mondis.DataType data_type = 4;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     *数据类型
     * </pre>
     *
     * <code>.mondis.DataType data_type = 4;</code>
     */
    mondis.Mondis.DataType getDataType();

    /**
     * <pre>
     *命令来源
     * </pre>
     *
     * <code>.mondis.CommandType command_type = 5;</code>
     */
    int getCommandTypeValue();
    /**
     * <pre>
     *命令来源
     * </pre>
     *
     * <code>.mondis.CommandType command_type = 5;</code>
     */
    mondis.Mondis.CommandType getCommandType();
  }
  /**
   * Protobuf type {@code mondis.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mondis.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      msgType_ = 0;
      content_ = "";
      resType_ = 0;
      dataType_ = 0;
      commandType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              resType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              commandType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mondis.Mondis.internal_static_mondis_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mondis.Mondis.internal_static_mondis_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mondis.Mondis.Message.class, mondis.Mondis.Message.Builder.class);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.mondis.MsgType msg_type = 1;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.mondis.MsgType msg_type = 1;</code>
     */
    public mondis.Mondis.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      mondis.Mondis.MsgType result = mondis.Mondis.MsgType.valueOf(msgType_);
      return result == null ? mondis.Mondis.MsgType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RES_TYPE_FIELD_NUMBER = 3;
    private int resType_;
    /**
     * <pre>
     *执行结果类型
     * </pre>
     *
     * <code>.mondis.ExecResType res_type = 3;</code>
     */
    public int getResTypeValue() {
      return resType_;
    }
    /**
     * <pre>
     *执行结果类型
     * </pre>
     *
     * <code>.mondis.ExecResType res_type = 3;</code>
     */
    public mondis.Mondis.ExecResType getResType() {
      @SuppressWarnings("deprecation")
      mondis.Mondis.ExecResType result = mondis.Mondis.ExecResType.valueOf(resType_);
      return result == null ? mondis.Mondis.ExecResType.UNRECOGNIZED : result;
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 4;
    private int dataType_;
    /**
     * <pre>
     *数据类型
     * </pre>
     *
     * <code>.mondis.DataType data_type = 4;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *数据类型
     * </pre>
     *
     * <code>.mondis.DataType data_type = 4;</code>
     */
    public mondis.Mondis.DataType getDataType() {
      @SuppressWarnings("deprecation")
      mondis.Mondis.DataType result = mondis.Mondis.DataType.valueOf(dataType_);
      return result == null ? mondis.Mondis.DataType.UNRECOGNIZED : result;
    }

    public static final int COMMAND_TYPE_FIELD_NUMBER = 5;
    private int commandType_;
    /**
     * <pre>
     *命令来源
     * </pre>
     *
     * <code>.mondis.CommandType command_type = 5;</code>
     */
    public int getCommandTypeValue() {
      return commandType_;
    }
    /**
     * <pre>
     *命令来源
     * </pre>
     *
     * <code>.mondis.CommandType command_type = 5;</code>
     */
    public mondis.Mondis.CommandType getCommandType() {
      @SuppressWarnings("deprecation")
      mondis.Mondis.CommandType result = mondis.Mondis.CommandType.valueOf(commandType_);
      return result == null ? mondis.Mondis.CommandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != mondis.Mondis.MsgType.DATA.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (resType_ != mondis.Mondis.ExecResType.OK.getNumber()) {
        output.writeEnum(3, resType_);
      }
      if (dataType_ != mondis.Mondis.DataType.SYNC_DATA.getNumber()) {
        output.writeEnum(4, dataType_);
      }
      if (commandType_ != mondis.Mondis.CommandType.CLIENT_COMMAND.getNumber()) {
        output.writeEnum(5, commandType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != mondis.Mondis.MsgType.DATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (resType_ != mondis.Mondis.ExecResType.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, resType_);
      }
      if (dataType_ != mondis.Mondis.DataType.SYNC_DATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, dataType_);
      }
      if (commandType_ != mondis.Mondis.CommandType.CLIENT_COMMAND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, commandType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mondis.Mondis.Message)) {
        return super.equals(obj);
      }
      mondis.Mondis.Message other = (mondis.Mondis.Message) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (resType_ != other.resType_) return false;
      if (dataType_ != other.dataType_) return false;
      if (commandType_ != other.commandType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + RES_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + resType_;
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + COMMAND_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + commandType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mondis.Mondis.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mondis.Mondis.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mondis.Mondis.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mondis.Mondis.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mondis.Mondis.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mondis.Mondis.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mondis.Mondis.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mondis.Mondis.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mondis.Mondis.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mondis.Mondis.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mondis.Mondis.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mondis.Mondis.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mondis.Mondis.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mondis.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mondis.Message)
        mondis.Mondis.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mondis.Mondis.internal_static_mondis_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mondis.Mondis.internal_static_mondis_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mondis.Mondis.Message.class, mondis.Mondis.Message.Builder.class);
      }

      // Construct using mondis.Mondis.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        content_ = "";

        resType_ = 0;

        dataType_ = 0;

        commandType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mondis.Mondis.internal_static_mondis_Message_descriptor;
      }

      @java.lang.Override
      public mondis.Mondis.Message getDefaultInstanceForType() {
        return mondis.Mondis.Message.getDefaultInstance();
      }

      @java.lang.Override
      public mondis.Mondis.Message build() {
        mondis.Mondis.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mondis.Mondis.Message buildPartial() {
        mondis.Mondis.Message result = new mondis.Mondis.Message(this);
        result.msgType_ = msgType_;
        result.content_ = content_;
        result.resType_ = resType_;
        result.dataType_ = dataType_;
        result.commandType_ = commandType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mondis.Mondis.Message) {
          return mergeFrom((mondis.Mondis.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mondis.Mondis.Message other) {
        if (other == mondis.Mondis.Message.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.resType_ != 0) {
          setResTypeValue(other.getResTypeValue());
        }
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (other.commandType_ != 0) {
          setCommandTypeValue(other.getCommandTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mondis.Mondis.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mondis.Mondis.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.mondis.MsgType msg_type = 1;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.mondis.MsgType msg_type = 1;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.mondis.MsgType msg_type = 1;</code>
       */
      public mondis.Mondis.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        mondis.Mondis.MsgType result = mondis.Mondis.MsgType.valueOf(msgType_);
        return result == null ? mondis.Mondis.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.mondis.MsgType msg_type = 1;</code>
       */
      public Builder setMsgType(mondis.Mondis.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.mondis.MsgType msg_type = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int resType_ = 0;
      /**
       * <pre>
       *执行结果类型
       * </pre>
       *
       * <code>.mondis.ExecResType res_type = 3;</code>
       */
      public int getResTypeValue() {
        return resType_;
      }
      /**
       * <pre>
       *执行结果类型
       * </pre>
       *
       * <code>.mondis.ExecResType res_type = 3;</code>
       */
      public Builder setResTypeValue(int value) {
        resType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行结果类型
       * </pre>
       *
       * <code>.mondis.ExecResType res_type = 3;</code>
       */
      public mondis.Mondis.ExecResType getResType() {
        @SuppressWarnings("deprecation")
        mondis.Mondis.ExecResType result = mondis.Mondis.ExecResType.valueOf(resType_);
        return result == null ? mondis.Mondis.ExecResType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *执行结果类型
       * </pre>
       *
       * <code>.mondis.ExecResType res_type = 3;</code>
       */
      public Builder setResType(mondis.Mondis.ExecResType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行结果类型
       * </pre>
       *
       * <code>.mondis.ExecResType res_type = 3;</code>
       */
      public Builder clearResType() {
        
        resType_ = 0;
        onChanged();
        return this;
      }

      private int dataType_ = 0;
      /**
       * <pre>
       *数据类型
       * </pre>
       *
       * <code>.mondis.DataType data_type = 4;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *数据类型
       * </pre>
       *
       * <code>.mondis.DataType data_type = 4;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据类型
       * </pre>
       *
       * <code>.mondis.DataType data_type = 4;</code>
       */
      public mondis.Mondis.DataType getDataType() {
        @SuppressWarnings("deprecation")
        mondis.Mondis.DataType result = mondis.Mondis.DataType.valueOf(dataType_);
        return result == null ? mondis.Mondis.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *数据类型
       * </pre>
       *
       * <code>.mondis.DataType data_type = 4;</code>
       */
      public Builder setDataType(mondis.Mondis.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据类型
       * </pre>
       *
       * <code>.mondis.DataType data_type = 4;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private int commandType_ = 0;
      /**
       * <pre>
       *命令来源
       * </pre>
       *
       * <code>.mondis.CommandType command_type = 5;</code>
       */
      public int getCommandTypeValue() {
        return commandType_;
      }
      /**
       * <pre>
       *命令来源
       * </pre>
       *
       * <code>.mondis.CommandType command_type = 5;</code>
       */
      public Builder setCommandTypeValue(int value) {
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令来源
       * </pre>
       *
       * <code>.mondis.CommandType command_type = 5;</code>
       */
      public mondis.Mondis.CommandType getCommandType() {
        @SuppressWarnings("deprecation")
        mondis.Mondis.CommandType result = mondis.Mondis.CommandType.valueOf(commandType_);
        return result == null ? mondis.Mondis.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *命令来源
       * </pre>
       *
       * <code>.mondis.CommandType command_type = 5;</code>
       */
      public Builder setCommandType(mondis.Mondis.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        commandType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令来源
       * </pre>
       *
       * <code>.mondis.CommandType command_type = 5;</code>
       */
      public Builder clearCommandType() {
        
        commandType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mondis.Message)
    }

    // @@protoc_insertion_point(class_scope:mondis.Message)
    private static final mondis.Mondis.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mondis.Mondis.Message();
    }

    public static mondis.Mondis.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mondis.Mondis.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mondis_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mondis_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mondis.proto\022\006mondis\"\264\001\n\007Message\022!\n\010ms" +
      "g_type\030\001 \001(\0162\017.mondis.MsgType\022\017\n\007content" +
      "\030\002 \001(\t\022%\n\010res_type\030\003 \001(\0162\023.mondis.ExecRe" +
      "sType\022#\n\tdata_type\030\004 \001(\0162\020.mondis.DataTy" +
      "pe\022)\n\014command_type\030\005 \001(\0162\023.mondis.Comman" +
      "dType*L\n\013ExecResType\022\006\n\002OK\020\000\022\020\n\014SYNTAX_E" +
      "RROR\020\001\022\022\n\016INTERNAL_ERROR\020\002\022\017\n\013LOGIC_ERRO" +
      "R\020\003*.\n\007MsgType\022\010\n\004DATA\020\000\022\013\n\007COMMAND\020\001\022\014\n" +
      "\010EXEC_RES\020\002*:\n\010DataType\022\r\n\tSYNC_DATA\020\000\022\017" +
      "\n\013CONTROL_MSG\020\001\022\016\n\nHEART_BEAT\020\002*m\n\013Comma" +
      "ndType\022\022\n\016CLIENT_COMMAND\020\000\022\022\n\016MASTER_COM" +
      "MAND\020\001\022\020\n\014PEER_COMMAND\020\002\022\021\n\rSLAVE_FORWAR" +
      "D\020\003\022\021\n\rTIMER_COMMAND\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mondis_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mondis_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mondis_Message_descriptor,
        new java.lang.String[] { "MsgType", "Content", "ResType", "DataType", "CommandType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
